spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: stentledbclient
      password: asauseryoucanonlyeatmysocks
      authentication-database: admin
      database: oauth

server:
  servlet:
    context-path: /uaa
  port: 7002